import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/provider/auth-provider";
import { currentFamily } from "@/lib/current-family";
import StoreProvider from "@/components/provider/redux-store-provider";
import { ModalProvider } from "@/components/provider/modal-provider";
import { currentMember } from "@/lib/current-member";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const family = await currentFamily()
  const member = await currentMember()


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <StoreProvider>
          <AuthProvider session={{family,member}}>
            <ModalProvider />
            {children}
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
