export const MODAL_TYPE = {
    ALERT_MODAL: "ALERT_MODAL",
    MEMBER_LOGIN: "MEMBER_LOGIN",
    MEMBER_REGISTER: "MEMBER_REGISTER",
    F_TRX_NAME: 'F_TRX_NAME',
    F_BANK_ACCOUNT: 'F_BANK_ACCOUNT',
    F_TRX: 'F_TRX',
    M_TRX_NAME: 'M_TRX_NAME',
    M_TRX: 'M_TRX',
    F_SHOPKEEPER: 'F_SHOPKEEPER',
    F_GIVE_LOAN: 'F_GIVE_LOAN',
    F_TAKE_LOAN: 'F_TAKE_LOAN',
    F_LOAN_PROVIDER: 'F_LOAN_PROVIDER',
    F_LOAN_RECIPIENT: 'F_LOAN_RECIPIENT',
    F_SHOPKEEPER_PURCHASE_DUE: 'F_SHOPKEEPER_PURCHASE_DUE',
    F_SHOPKEEPER_BILL: 'F_SHOPKEEPER_BILL',
    F_MEMBER:'F_MEMBER'
} as const